version: "3.7"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:1.27.3
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_DIAGNOSTICS_ENABLED=${N8N_DIAGNOSTICS_ENABLED:-false}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-Europe/Moscow}
    volumes:
      - n8n_data:/home/node/.n8n
    command: ["start", "--tunnel"]

volumes:
  n8n_data:
    external: true
