version: "3.7"

services:
  flowise:
    image: flowiseai/flowise:1.5.0
    restart: always
    labels:
      #   - traefik.http.routers.flowise.tls.certresolver=staging
      - traefik.http.routers.flowise.tls.certresolver=production
      - traefik.enable=true
      - traefik.http.routers.flowise.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)
      - traefik.http.routers.flowise.tls=true
      - traefik.http.routers.flowise.entrypoints=web,websecure
      - traefik.http.middlewares.flowise.headers.SSLRedirect=true
      - traefik.http.middlewares.flowise.headers.STSSeconds=315360000
      - traefik.http.middlewares.flowise.headers.browserXSSFilter=true
      - traefik.http.middlewares.flowise.headers.contentTypeNosniff=true
      - traefik.http.middlewares.flowise.headers.forceSTSHeader=true
      - traefik.http.middlewares.flowise.headers.SSLHost=${DOMAIN_NAME}
      - traefik.http.middlewares.flowise.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.flowise.headers.STSPreload=true
      - traefik.http.routers.flowise.middlewares=flowise@docker
    environment:
      - PORT=${PORT}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - IFRAME_ORIGINS=${IFRAME_ORIGINS}
      - FLOWISE_USERNAME=${FLOWISE_USERNAME}
      - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
      - FLOWISE_FILE_SIZE_LIMIT=${FLOWISE_FILE_SIZE_LIMIT}
      - DEBUG=${DEBUG}
      - DATABASE_PATH=${DATABASE_PATH}
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SSL=${DATABASE_SSL}
      - DATABASE_SSL_KEY_BASE64=${DATABASE_SSL_KEY_BASE64}
      - APIKEY_PATH=${APIKEY_PATH}
      - SECRETKEY_PATH=${SECRETKEY_PATH}
      - FLOWISE_SECRETKEY_OVERWRITE=${FLOWISE_SECRETKEY_OVERWRITE}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_PATH=${LOG_PATH}
      - DISABLE_FLOWISE_TELEMETRY=${DISABLE_FLOWISE_TELEMETRY}
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
    volumes:
      - ~/.flowise:/root/.flowise
    networks:
      - traefik
    command: /bin/sh -c "sleep 3; flowise start"

networks:
  traefik:
    external: true
